### ISSUE TITLE
Small remarks after guided HOL

### ISSUE THREAD

**Issue by iBoonz** [Microsoft/MCW-Internet-of-Things#1]
Exercise 4.11
SELECT AVG(temp) AS Average**,** id
INTO powerbi
FROM temps
GROUP BY TumblingWindow**(minute,** 5**),** id

with the asterix (*), the query will not work.

Exercise 5 --> There are no steps that inform about the storage account, Add steps to add storage account

Thanks for the lab!

**Comment by joelhulen** [comment]
Addressed in latest update (june-2018-update branch). September changes appended. Awaiting review for merge into master.
