### ISSUE TITLE
Getting Path error

### ISSUE THREAD

**Issue by fasalzaman** [Microsoft/MCW-Internet-of-Things#12]
While running the following command on Databriks **(Exercise 4 > Task 4 > Step 17)** I am getting a path error.
```
#Create a Dataframe containing data from all the files in blob storage, regardless of the folder they are located within.
df = spark.read.options(header='true', inferSchema='true').csv("dbfs:/mnt/smartmeters/*/*/*.csv",header=True)
print(df.dtypes)
```
 I am getting an error that the path "dbfs:/mnt/smartmeters/*/*/*.csv" is not correct.

Instead of that, I tried the following command and it solved the error.
```
#Create a Dataframe containing data from all the files in blob storage, regardless of the folder they are located within.
df = spark.read.options(header='true', inferSchema='true').csv("dbfs:/mnt/smartmeters/*/*/*/*/*.csv",header=True)
print(df.dtypes)
```

**Comment by joelhulen** [comment]
I was not able to reproduce this error, but I've added a note in the lab to change the path if users encounter the same error.
