### ISSUE TITLE
This MCW is tied to only MSDN subscription

### ISSUE THREAD

**Issue by Jiihaa** [Microsoft/MCW-Internet-of-Things#14]
This MCW requires that the user is using MSDN subscription, as Visual Studio Community with Windows Server is not available to another subscription types, such as Pay As You Go or Azure Passes. There is no mention about this requirement.

**Comment by DawnmarieDesJardins** [comment]
Thanks Jani!  We are currently working on updating this workshop, I've brought this to the author's attention.

**Comment by joelhulen** [comment]
@Jiihaa I have updated this information in the Before the Hands-on Lab file in my fork. It will be included in my PR once the updates to this MCW are completed.

To clarify, this only affects using a VM for this lab. Everything else works with Pay As You Go.
