### ISSUE TITLE
March updates to Trainer presentation

### ISSUE THREAD

**Issue by Teodelas** [Microsoft/MCW-Internet-of-Things#17]
For the Trainer presentation:
- Slide 6: I don't think we refer to IoT Suite anymore.  May need marketing to confirm.
- Slide 17: HTTP/1 Polling or AMQP is mentioned.  Why isn't MQTT listed?  MQTT is the preferred communication protocol.  In terms of 'recommendations': 1. MQTT, 2. AMQP, 3. HTTP
- Slide 18: In the notes section we mention pre-configured solutions and IoT Suite.  I think the new terminology is IoT Solution Accelerators.

**Comment by joelhulen** [comment]
I can make these changes. There are other pending changes in the PR. I'll update the PR so these will be included when it's merged.

**Comment by joelhulen** [comment]
The PR has been updated with these changes.

**Comment by Teodelas** [comment]
Am I submitting 'issues' correctly? Should I just edit the documents directly instead?

**Comment by joelhulen** [comment]
Submitting issues is the correct procedure. If you want to edit the documents and submit a pull request, that's fine. But it's better I made the changes this time since I already have an open pull request

**Comment by Teodelas** [comment]
OK.  Yeah, since there’s a March PR I’ll just submit issues.  Just making sure I’m following the most efficient path.
