### ISSUE TITLE
'DeviceState' could not be found

### ISSUE THREAD

**Issue by benzadeh** [Microsoft/MCW-Internet-of-Things#19]
Not able to run the simulator following the instructions. Getting below error 

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'DeviceState' could not be found (are you missing a using directive or an assembly reference?)	SmartMeterSimulator	C:\MCW-Internet-of-Things-master\MCW-Internet-of-Things-master\Hands-on lab\lab-files\starter-project\SmartMeterSimulator\Sensor.cs	18	Active

**Comment by joelhulen** [comment]
There is a pending pull request which includes changes to the simulator code. Could you try out the new version and see if it works?

**Comment by benzadeh** [comment]
Yes, thanks that fixed the issue and I was able to run the simulator. sensor.cs was missing below
public enum DeviceState
    {
        Registered,
        Installed,
        Activated,
        Ready,
        Transmit
    }
    public enum SensorState
    {
        Cold,
        Normal,
        Hot
    }
