### ISSUE TITLE
Change Step 8 of task 3

### ISSUE THREAD

**Issue by falloutxAY** [Microsoft/MCW-Internet-of-Things#2]
In this [section ](https://github.com/Microsoft/MCW-Internet-of-Things/blob/master/HOL/Hands-on%20lab%20step-by%20step%20-%20Internet%20of%20Things.md#task-3-update-pandas-version-on-the-spark-cluster)

Under Step 8, change 

`sudo -HE /usr/bin/anaconda/bin/conda install pandas`

to 

`sudo -HE /usr/bin/anaconda/bin/conda install pandas=0.20.3`

The former causes an error when you are running the Scala code in Task 4, step 5

**Comment by joelhulen** [comment]
This no longer applies now that we've moved to using Azure Databricks. Changes are in the june-2018-update branch. Awaiting merge to master after review. Includes September test/fix changes as well.
