### ISSUE TITLE
Will this lab be updated to VS2019?

### ISSUE THREAD

**Issue by NoureenS** [microsoft/MCW-Internet-of-Things#20]
Lab uses VS2017.

**Comment by timahenning** [comment]
Yes, this will be upgraded to VS2019

**Comment by DawnmarieDesJardins** [comment]
Tagging this comment as an enhancement for the scheduled June test/fix.
Thanks! Dawnamrie

**Comment by givenscj** [comment]
Yes, June 2019 update will be with Visual Studio 2019.  Work is complete.

**Comment by mrfalafel** [comment]
September update is VS 2019 compatible, you can close this issue.

**Comment by DawnmarieDesJardins** [comment]
Closing issue, address in September 2019 update
