### ISSUE TITLE
September 2019 - Content update

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [microsoft/MCW-Internet-of-Things#23]
This MCW is scheduled for content update.
Solliance - please review current content, open issue #20 and open PR #22 and recommended updates for SME review.

**Comment by olivierbloch** [comment]
These seem reasonable

**Comment by kartben** [comment]
There are quite a few comments that weren't addressed during the previous review cycle and associated pull request (https://github.com/microsoft/MCW-Internet-of-Things/pull/16), it would be great if someone could have a look at these.

**Comment by DawnmarieDesJardins** [comment]
Closing with September 2019 update
