### ISSUE TITLE
Issue while running Command 3 in notebooks - Exercise 4 Task 4

### ISSUE THREAD

**Issue by Suraj2093** [microsoft/MCW-Internet-of-Things#27]
In Excercise 4 Task 4 the command 3 in notebook smartmeters giving an error. 

@DawnmarieDesJardins - please look into this as we have a workshop scheduled for 11th next week.

![image](https://user-images.githubusercontent.com/30050847/70348315-7671a680-1888-11ea-8226-cba351d5c332.png)

**Comment by raniaeg** [comment]
Could you please give this priority as we have hands-on lab for 40 candidates in Brussels on **11 December**? Appreciate your soonest feedback and attention.
Thanks,
Rania

**Comment by DawnmarieDesJardins** [comment]
@Suraj2093 @raniabayoumy @timahenning 
Thank you, we will do the best we can.  Please be advised we ask for 5 - 10 business days to resolve issues to give our authors adequate time to test and resolve.

**Comment by raniabayoumy** [comment]
Thanks very much indeed for your support on this @Dawnmarie<mailto:notifications@github.com> it’s much appreciated and noted.
Kind regards,
Rania

**Comment by givenscj** [comment]
Hi there,

This was due to the previous command failing due to it not having indention.  I have updated the code and added a note for attendees to watch for indentation in Python.  Update will be submitted along with the other updates today (12/10/19).

**Comment by raniabayoumy** [comment]
Thanks very much indeed, appreciate the swift action and support!
I tested the lab couple of hours ago and everything seems to be functioning perfectly.
Kind regards,
Rania

**Comment by raniabayoumy** [comment]
One other issue I just found whenever I click on the Before the hands-on lab setup<https://cloudworkshop.blob.core.windows.net/internet-of-things/Hands-on%20lab/Before%20the%20HOL%20-%20Internet%20of%20Things.md> link I get this:

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>BlobNotFound</Code>
<Message>
The specified blob does not exist. RequestId:5bfcc535-d01e-007f-6e79-af9d00000000 Time:2019-12-10T16:46:47.6056554Z
</Message>
</Error>

Please advise.
Thanks,
Rania
