### ISSUE TITLE
Exercise 3: Task 2:

### ISSUE THREAD

**Issue by SeeratArora** [microsoft/MCW-Internet-of-Things#29]
[Exercise 3: Task 2](https://github.com/microsoft/MCW-Internet-of-Things/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Internet%20of%20Things.md#task-2-visualize-hot-data-with-power-bi) Step 2: Dataset *avgtemps* is not showing up in PowerBI.

![image](https://user-images.githubusercontent.com/50323628/72347437-352dab80-36fe-11ea-91df-31c31d7b525b.png)

Can you please look into this?

**Comment by TheTrainingBoss** [comment]
It takes a few minutes from the time the avgtemps dataset is created till it shows up in Power Point.
I will add a not to the MCW reflecting the wait time till this dataset is appearing and showing in Power BI
Thanks
-Lino

**Comment by timahenning** [comment]
@SeeratArora Did waiting for the dataset work for you?

**Comment by SeeratArora** [comment]
Hi Tim,

I just completed Internet of Things and this time there was no issue, dataset was available. Everything went smooth.

Thanks,
Seerat

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by DawnmarieDesJardins** [comment]
Thanks Seerat!  Closing this issue as resolved.
