### ISSUE TITLE
June 2020 Update Suggestions

### ISSUE THREAD

**Issue by timahenning** [microsoft/MCW-Internet-of-Things#32]

**Comment by TheTrainingBoss** [comment]
Proposal for the June 30th update:

- Use Delta architecture instead of lambda architecture
- Include Edge Gateway Management
- Include how to monitor Telemetry for debugging

**Comment by DawnmarieDesJardins** [comment]
@timahenning @TheTrainingBoss 
Update suggestions address and close current issue #25.

**Comment by DawnmarieDesJardins** [comment]
Closing the June 2020 update suggestions issue.  This will now be a June test/fix
