### ISSUE TITLE
WDS trainer guide - Internet of Things: IoT Central

### ISSUE THREAD

**Issue by falloutxAY** [microsoft/MCW-Internet-of-Things#40]
https://github.com/microsoft/MCW-Internet-of-Things/blob/main/Whiteboard%20design%20session/WDS%20trainer%20guide%20-%20Internet%20of%20Things.md#checklist-of-preferred-objection-handling

IoT central has been re-positioned as aPaaS (application platform as a service) See here as a reference
https://docs.microsoft.com/en-us/azure/architecture/example-scenario/iot/iot-central-iot-hub-cheat-sheet

As such, will suggest to update the paragraph to reflect.

**Comment by codingbandit** [comment]
Noted and updated in the PR - thank you!

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #39
